<a href="https://colab.research.google.com/github/sudhanshumukherjeexx/PyTorch-Playground/blob/main/1.Exploring_PyTorch_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Programmed by Sudhanshu Mukherjee
* 10-15-2024: Collab Notebook
* 10-29-2024: Notebook updated with text

In this notebook, we are going to cover PyTorch Tensor Operations and cover the topics mentioned below:
#### 1. **Initializing Tensors**

1.1 Initializing 1D tensor  
1.2 Initializing 2D tensor  
1.3 Initializing 3D tensor  
1.4 Randomly initializing tensors  
1.5 Initializing tensors with specific values (e.g., all zeros, all ones, identity matrix, etc.)  
1.6 Initializing tensors with data types (int, float, etc.)

#### 2. **Mathematical Operations on Tensors**

2.1 Element-wise addition, subtraction, multiplication, and division  
2.2 Exponentiation and logarithms  
2.3 Summation and mean  
2.4 Max and min values, and their indices  
2.5 Broadcasting in tensor operations

#### 3. **Matrix Operations in PyTorch**

3.1 Matrix addition  
3.2 Matrix subtraction  
3.3 Matrix multiplication (element-wise and matrix product)  
3.4 Matrix division  
3.5 Transpose of a matrix  
3.6 Matrix inverse and determinant  
3.7 Reshaping and flattening tensors  
3.8 Slicing and indexing tensors

#### 4. **Tensor Concatenation and Stacking**

4.1 Concatenating tensors along different dimensions  
4.2 Stacking tensors vertically and horizontally

#### 5. **Converting between PyTorch Tensors and NumPy Arrays**

5.1 Converting NumPy arrays to PyTorch tensors  
5.2 Converting PyTorch tensors to NumPy arrays

#### 6. **Automatic Differentiation with PyTorch**

6.1 Creating tensors with `requires_grad=True`  
6.2 Computing gradients with `backward()`

### 1. Initializing Tensors

In [ ]:
import torch
import numpy as np

- Intializing 1D, 2D, 3D tensors

In [ ]:
tensor_1d = torch.tensor([1, 2, 3])
tensor_2d = torch.tensor([[1,2], [3,4]])
tensor_3d = torch.tensor([[[1,2], [3,4]],[[5,6], [7,8]]])

print(f"1D Tensor:\n{tensor_1d}\n\n 2D Tensor:\n{tensor_2d}\n\n 3D Tensor:\n{tensor_3d}")

1D Tensor:
tensor([1, 2, 3])

 2D Tensor:
tensor([[1, 2],
        [3, 4]])

 3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


- Randomly Intialized Tensors

In [ ]:
rand_tensor = torch.rand(3,3)
print(f"Random Tensor:\n {rand_tensor}")

Random Tensor:
 tensor([[0.5065, 0.1717, 0.6168],
        [0.7226, 0.9002, 0.1678],
        [0.9238, 0.8586, 0.9715]])


- Tensors Intialized with Specific values

In [ ]:
zero_tensor = torch.zeros(3,3)
one_tensor = torch.ones(3,3)
identity_tensor = torch.eye(3)


print(f"Zeros Tensor:\n{zero_tensor}\n\n Ones Tensor:\n{one_tensor}\n\n Identity Tensor:\n{identity_tensor}")

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

 Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

 Identity Tensor:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


- Tensors with Specific Data Types

In [ ]:
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

print(f"Float Tensor:\n{float_tensor}\n\n Int Tensor:\n{int_tensor}")

Float Tensor:
tensor([1., 2., 3.])

 Int Tensor:
tensor([1, 2, 3], dtype=torch.int32)


### 2. Mathematical Operations on Tensors

- Element-wise Operations

In [ ]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

print(f"Addition: {a + b}")

Addition: tensor([5., 7., 9.])


In [ ]:
print(f"Subtraction: {a - b}")

Subtraction: tensor([-3., -3., -3.])


In [ ]:
print(f"Multiplication: {a * b}")

Multiplication: tensor([ 4., 10., 18.])


In [ ]:
print(f"Division: {a / b}")

Division: tensor([0.2500, 0.4000, 0.5000])


In [ ]:
print(f"Raising to a Power of 2: {a ** 2}")

Raising to a Power of 2: tensor([1., 4., 9.])


In [ ]:
print(f"Applying Sin element-wise: {torch.sin(a)}")

Applying Sin element-wise: tensor([0.8415, 0.9093, 0.1411])


In [ ]:
print(f"Boolean Tests: {a == 10}")

Boolean Tests: tensor([False, False, False])


In [ ]:
print(f"Boolean Tests: {a < 10}")

Boolean Tests: tensor([True, True, True])


In [ ]:
print(f"AND operator: {(b<10) & (b>=2)}")

AND operator: tensor([True, True, True])


- Exponentiation and logarithm

In [ ]:
exp_tensor = torch.exp(a)
log_tensor = torch.log(b)

print(f"Exponentiation:\n{exp_tensor}\n\nLogarithm:\n{log_tensor}")

Exponentiation:
tensor([ 2.7183,  7.3891, 20.0855])

Logarithm:
tensor([1.3863, 1.6094, 1.7918])


- Summation and Mean

In [ ]:
sum_a = torch.sum(a)
mean_b = torch.mean(b)

print(f"Sum of a: {sum_a}\n\nMean of b: {mean_b}")

Sum of a: 6.0

Mean of b: 5.0


- Max and Min values, and their indices

In [ ]:
max_value, max_idx = torch.max(b, dim=0)
min_value, min_idx = torch.min(a, dim=0)

print(f"Max value of b: {max_value} at index {max_idx}")
print(f"Min value of a: {min_value} at index {min_idx}")

Max value of b: 6.0 at index 2
Min value of a: 1.0 at index 0


- Broadcasting Example

Things to Remember:
- Broadcasting allows for operations on tensors of different shapes without explicitly reshaping them.
- PyTorch automatically expands smaller dimensions by "repeating" elements along the required axis.
- This makes operations like addition more efficient and easier to write without needing to manually adjust tensor shapes.

In [ ]:
x = torch.tensor([[1], [2], [3]])
y = torch.tensor([1, 2, 3])

# broadcaasts y to match the shape of x
result = x + y
print(f"Broadcasting result: \n{result}")

Broadcasting result: 
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])


### 3. Matrix Operations in PyTorch

- Matrix Addition

In [ ]:
matrix1 = torch.tensor([[1,2] , [3,4]])
matrix2 = torch.tensor([[5,6] , [7,8]])

print(f"Matrix Addition: \n{matrix1 + matrix2}\n")
print(f"Matrix Subtraction: \n{matrix1 - matrix2}\n")
print(f"Element-wise Multiplication:\n{matrix1 * matrix2}")

Matrix Addition: 
tensor([[ 6,  8],
        [10, 12]])

Matrix Subtraction: 
tensor([[-4, -4],
        [-4, -4]])

Element-wise Multiplication:
tensor([[ 5, 12],
        [21, 32]])


- Matrix Multiplication (dot product)

In [ ]:
matmul_result = torch.matmul(matrix1, matrix2)
print(f"Matrix Multiplication (dot product): \n{matmul_result}")

Matrix Multiplication (dot product): 
tensor([[19, 22],
        [43, 50]])


- Matrix Transpose

In [ ]:
transpose_matrix = matrix1.T
print(f"Transpose of Matrix:\n{transpose_matrix}")

Transpose of Matrix:
tensor([[1, 3],
        [2, 4]])


- Matrix inverse and determinant

- Matrix Inverse Formula


![Matrix Inverse](https://drive.google.com/uc?export=view&id=1mUS0txcENmSw7dRYDvwzDf6i_fIh69LQ)

- Matrix Determinant Formula

![Matrix Determinant](https://drive.google.com/uc?export=view&id=1Kxzk8UF83faStAdlCJclLKl7nxzt8ndQ)

In [ ]:
matrix3 = torch.tensor([[2.0 , 1.0], [1.0, 3.0]])
inv_matrix = torch.inverse(matrix3)
det_matrix = torch.det(matrix3)
print(f"Inverse of Matrix:\n{inv_matrix}\n\nDeterminant of Matrix:\n{det_matrix}")

Inverse of Matrix:
tensor([[ 0.6000, -0.2000],
        [-0.2000,  0.4000]])

Determinant of Matrix:
5.0


- Reshaping Tensors

- `flatten()` is specifically designed to collapse dimensions into a single dimension.
- `view()` is a general reshaping function that can reshape a tensor into any shape, not just 1D.


In [ ]:
reshaped_tensor = matrix1.view(4)
reshaped_tensor_2 = matrix1.view(4,1)
flattened_tensor = matrix1.flatten()


print(f"Matrix1:\n{matrix1}\n\nReshaped Tensor:\n{reshaped_tensor}\n\nReshaped Tensor 2:\n{reshaped_tensor_2}\n\nFlattened Tensor: {flattened_tensor}")

Matrix1:
tensor([[1, 2],
        [3, 4]])

Reshaped Tensor:
tensor([1, 2, 3, 4])

Reshaped Tensor 2:
tensor([[1],
        [2],
        [3],
        [4]])

Flattened Tensor: tensor([1, 2, 3, 4])


- Slicing Tensors

In [ ]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

slicing_first_row = matrix[0, :]
print(f"Slicing First Row:\n{slicing_first_row}\n\n")

slicing_second_column = matrix[:,1]
print(f"Slicing Second Column:\n{slicing_second_column}\n\n")

slicing_2x2_submatrix = matrix[:2, :2]
print(f"Slicing 2x2 Submatrix:\n{slicing_2x2_submatrix}\n\n")

slicing_with_steps_second_row = matrix[::2, :]
print(f"Slicing with steps - second row:\n{slicing_with_steps_second_row}\n\n")

slicing_with_steps_second_column = matrix[:, ::2]
print(f"Slicing with steps - Second Column:\n{slicing_with_steps_second_column}\n\n")

slicing_with_negative_index = matrix[-1, :]
print(f"Slicing with Negative Index:\n{slicing_with_negative_index}\n\n")

slicing_with_negative_index_row = matrix[-1, :]
print(f"Slicing with Negative Index - Row:\n{slicing_with_negative_index_row}\n\n")

slicing_with_negative_index_column = matrix[:, -1]
print(f"Slicing with Negative Index - Column:\n{slicing_with_negative_index_column}\n\n")

slicing_multiple_rows_and_columns = matrix[1:3, 1:3]
print(f"Slicing Multiple Rows and Columns:\n{slicing_multiple_rows_and_columns}\n\n")

slicing_reverse_rows = torch.flip(matrix, [0])
print(f"slicing Reverse Rows:\n{slicing_reverse_rows}\n\n")

slicing_reverse_columns = torch.flip(matrix, [1])
print(f"slicing Reverse Columns:\n{slicing_reverse_columns}\n\n")

extracting_diagonal_elements = torch.diag(matrix)
print(f"Extracting Diagonal Elements:\n{extracting_diagonal_elements}\n\n")

Slicing First Row:
tensor([1, 2, 3])


Slicing Second Column:
tensor([2, 5, 8])


Slicing 2x2 Submatrix:
tensor([[1, 2],
        [4, 5]])


Slicing with steps - second row:
tensor([[1, 2, 3],
        [7, 8, 9]])


Slicing with steps - Second Column:
tensor([[1, 3],
        [4, 6],
        [7, 9]])


Slicing with Negative Index:
tensor([7, 8, 9])


Slicing with Negative Index - Row:
tensor([7, 8, 9])


Slicing with Negative Index - Column:
tensor([3, 6, 9])


Slicing Multiple Rows and Columns:
tensor([[5, 6],
        [8, 9]])


slicing Reverse Rows:
tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])


slicing Reverse Columns:
tensor([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]])


Extracting Diagonal Elements:
tensor([1, 5, 9])




### 4. Tensor Concatenation and Stacking

In [ ]:
print(f"Matrix 1:\n {matrix1}\n\n")
print(f"Matrix 2:\n {matrix2}\n\n")

Matrix 1:
 tensor([[1, 2],
        [3, 4]])


Matrix 2:
 tensor([[5, 6],
        [7, 8]])




- Concatenating Tensors along different dimensions

In [ ]:
concat_tensor = torch.cat((matrix1, matrix2), dim=0)
print(f"Concatenated Tensor: \n{concat_tensor}")

Concatenated Tensor: 
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
concat_tensor = torch.cat((matrix1, matrix2), dim=1)
print(f"Concatenated Tensor: \n{concat_tensor}")

Concatenated Tensor: 
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


- Stacking Tensors

In [ ]:
stacked_tensor = torch.stack((matrix1, matrix2), dim=0)
print(f"Stacked Tensor:\n{stacked_tensor}")

Stacked Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
stacked_tensor = torch.stack((matrix1, matrix2), dim=1)
print(f"Stacked Tensor:\n{stacked_tensor}")

Stacked Tensor:
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


### 5. Converting between PyTorch Tensors and NumPy Arrays

- Converting NumPy arrays to PyTorch Tensors

In [ ]:
np_array = np.array([1, 2, 3])
torch_tensor_from_numpy = torch.from_numpy(np_array)
print(f"Numpy to Tensor: {torch_tensor_from_numpy}")

Numpy to Tensor: tensor([1, 2, 3])


- Converting PyTorch tensors to NumPy arrays

In [ ]:
tensor_to_numpy = torch_tensor_from_numpy.numpy()
print(f"Tensor to NumPy: {tensor_to_numpy}")

Tensor to NumPy: [1 2 3]


### 6. Automatic Differentiation

In [ ]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x**2
# backpropogate
y.backward(torch.ones_like(x))
print(f"Gradients: {x.grad}")

Gradients: tensor([4., 6.])
